# WINDOWS CONFIGURATION
[font]
size = 12.0

[font.offset]
x = 0
y = 1

[colors]
draw_bold_text_with_bright_colors = true

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Control"

[window]
dynamic_padding = false
opacity = 1.0
title = "Alacritty"
startup_mode = "Windowed"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 1
